name: Execute code examples

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
    run-tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
      
        steps:
            - uses: actions/checkout@v4    
            
            - name: Install stable toolchain
              uses: dtolnay/rust-toolchain@master
              with:
                toolchain: stable
            
            - name: Install mdbook
              run: cargo install mdbook
            - name: Run tests
              run: mdbook test
